# all the classes to be predicted by the model
CLASSES = [
    "Tomato  Late_blight",
    "Tomato  healthy",
    "Grape   healthy",
    "Orange  Haunglongbing_(Citrus_greening)",
    "Soybean healthy",
    "Squash  Powdery_mildew",
    "Potato  healthy",
    "maize   Northern_Leaf_Blight",
    "Tomato  Early_blight",
    "Tomato  Septoria_leaf_spot",
    "maize   Gray_leaf_spot",
    "Strawberry Leaf_scorch",
    "Peach   healthy",
    "Apple   Apple_scab",
    "Tomato  Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato  Bacterial_spot",
    "Apple   Black_rot",
    "Blueberry  healthy",
    "Cherry  Powdery_mildew",
    "Peach   Bacterial_spot",
    "Apple   Cedar_apple_rust",
    "Tomato     Target_Spot",
    "Pepper_bell  healthy",
    "Grape   Leaf_blight_(Isariopsis_Leaf_Spot)",
    "Potato  Late_blight",
    "Tomato  Tomato_mosaic_virus",
    "Strawberry  healthy",
    "Apple   healthy",
    "Grape   Black_rot",
    "Potato  arly_blight",
    "Cherry  healthy",
    "maize   Common_rust_",
    "Grape   Esca_(Black_Measles)",
    "Raspberry  healthy",
    "Tomato  Leaf_Mold",
    "Tomato  Two-spotted_spider_mite",
    "Pepper_bell Bacterial_spot",
    "maize  healthy",
]

TOMATO_CLASSES = [
    "Tomato___Late_blight",
    "Tomato___healthy",
    "Tomato___Early_blight",
    "Tomato___Septoria_leaf_spot",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato___Bacterial_spot",
    "Tomato___Target_Spot",
    "Tomato___Tomato_mosaic_virus",
    "Tomato___Leaf_Mold",
    "Tomato___Spider_mites Two-spotted_spider_mite",
]

MAIZE_CLASSES = ["Maize Common_Rust", "Maize Blight", "Maize Healthy", "Maize Gray_Leaf_Spot"]
